## Selecting DataFrame Data

In [1]:
import pandas as pd
file_path = '../../data/USCG.Search.Rescue.Stats.csv'
df = pd.read_csv(file_path)
df.head()

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1964,NaN,41525,NaN,2932,NaN,NaN,NaN,NaN,NaN
1965,NaN,38586,NaN,1984,NaN,NaN,NaN,NaN,NaN
1966,NaN,43366,NaN,2629,NaN,NaN,NaN,NaN,NaN
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN

### Boolean Mask

In [ ]:
# Creamos una máscara de booleanos con el mismo tamaño que el DataFrame, inicialmente con todos los valores en False
# _ significa que no necesitamos el valor de la variable, solo queremos repetir la operación len(df) veces
mask = [False for _ in range(len(df))] 
# Establecemos los valores de la máscara a True para las filas que queremos seleccionar (en este caso, las filas 3 a 6)
mask[3:7] = [True] * 4 
mask

[False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [3]:
df[mask]

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN
1969,NaN,48720,NaN,2050,NaN,NaN,NaN,NaN,NaN
1970,44975.0,52183,62286.0,4135,1783.0,NaN,1783.0,NaN,NaN

In [4]:
# Otra forma de seleccionar filas usando la máscara es con loc, que es un indexador basado en etiquetas. En este caso, como la máscara es un array de booleanos, loc seleccionará las filas correspondientes a los valores True en la máscara.
df.loc[mask]

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN
1969,NaN,48720,NaN,2050,NaN,NaN,NaN,NaN,NaN
1970,44975.0,52183,62286.0,4135,1783.0,NaN,1783.0,NaN,NaN

### Creating mask using comparison operators

In [5]:
mask = df.loc[:, 'Lives Lost After CG Notification'] < df.loc[:, 'Lives Lost Before CG Notification']
mask

1964    False
1965    False
1966    False
1967    False
1968    False
1969    False
1970    False
1971    False
1972    False
1973    False
1974    False
1975    False
1976    False
1977    False
1978    False
1979     True
1980     True
1981     True
1982     True
1983     True
1984     True
1985     True
1986     True
1987     True
1988     True
1989     True
1990     True
1991     True
1992     True
1993     True
1994     True
1995     True
1996     True
1997     True
1998     True
1999     True
2000     True
2001     True
2002     True
2003     True
2004     True
2005     True
2006     True
2007     True
2008     True
2009     True
2010     True
2011     True
2012     True
2013     True
2014     True
2015     True
dtype: bool

In [6]:
df[mask]

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1979,72517.0,79858,92117.0,5747,949.0,672.0,1621.0,NaN,NaN
1980,73345.0,81476,93726.0,6868,1235.0,586.0,1821.0,NaN,NaN
1981,71781.0,78951,91432.0,6339,1080.0,637.0,1717.0,NaN,NaN
1982,68552.0,75717,87715.0,5675,1359.0,446.0,1805.0,NaN,NaN
1983,63980.0,72585,85796.0,5946,1121.0,640.0,1761.0,NaN,NaN
1984,57431.0,66073,80698.0,5645,1148.0,319.0,1467.0,NaN,NaN
1985,60775.0,70237,88449.0,6497,1076.0,259.0,1335.0,NaN,NaN
1986,51765.0,68805,89318.0,4307,475.0,180.0,655.0,NaN,NaN
1987,55998.0,66656,87211.0,5785,1015.0,576.0,1591.0,NaN,NaN
1988,54199.0,63446,83616.0,4307,583.0,449.0,1032.0,NaN,NaN
1989,52776.0,64027,81862.0,3981,461.0,646.0,1107.0,NaN,NaN
1990,53097.0,64971,84033.0,4407,463.0,622.0,1085.0,NaN,NaN
1991,52782.0,66409,84872.0,5465,368.0,748.0,1116.0,NaN,NaN
1992,53294.0,69856,88388.0,5543,399.0,540.0,939.0,NaN,NaN
1993,53026.0,69784,88147.0,5826,415.0,800.0,1215.0,NaN,NaN
1994,53899.0,70337,108758.0,7889,338.0,593.0,931.0,NaN,NaN
1995,49704.0,63679,110267.0,4453,304.0,468.0,772.0,NaN,NaN
1996,43553.0,55710,98423.0,5047,367.0,611.0,978.0,NaN,NaN
1997,41096.0,52141,91722.0,3897,290.0,454.0,744.0,NaN,NaN
1998,37218.0,46602,83307.0,3194,188.0,418.0,606.0,NaN,NaN
1999,39844.0,50622,89635.0,3743,180.0,353.0,533.0,NaN,NaN
2000,40214.0,48226,57697.0,3400,239.0,779.0,1018.0,304.0,NaN
2001,39457.0,49502,59015.0,4010,297.0,413.0,710.0,515.0,NaN
2002,36763.0,46643,54609.0,3661,236.0,399.0,635.0,339.0,NaN
2003,31429.0,51389,33117.0,5192,263.0,409.0,672.0,496.0,NaN
2004,32418.0,59995,33460.0,5557,281.0,502.0,783.0,691.0,NaN
2005,29646.0,52741,30779.0,5635,324.0,521.0,845.0,603.0,NaN
2006,28151.0,45910,28583.0,5275,328.0,452.0,780.0,664.0,NaN
2007,26927.0,47517,26586.0,5200,300.0,492.0,792.0,732.0,NaN
2008,24213.0,44931,25475.0,4900,291.0,534.0,825.0,435.0,NaN
2009,23545.0,47497,24644.0,4882,261.0,555.0,816.0,578.0,NaN
2010,22229.0,46407,23145.0,4362,263.0,552.0,815.0,409.0,NaN
2011,20512.0,43954,21566.0,3793,259.0,476.0,735.0,392.0,NaN
2012,19787.0,43940,21609.0,4037,284.0,429.0,713.0,440.0,NaN
2013,17803.0,38272,19420.0,3753,226.0,425.0,651.0,252.0,NaN
2014,17508.0,38282,19032.0,3443,170.0,425.0,595.0,308.0,NaN
2015,16456.0,37215,18781.0,3536,169.0,434.0,603.0,330.0,NaN

### Pandas Boolean operators

1. And: &
2. Or: |
3. Not: ~

In [7]:
df.describe()

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
count,46.000000,52.000000,46.000000,52.000000,46.000000,37.000000,46.000000,16.000000,0.0
mean,46296.608696,58013.769231,67666.586957,4339.230769,670.956522,508.486486,1079.956522,468.000000,NaN
std,17438.646933,13480.714228,29300.537271,1334.134847,499.839128,134.761028,394.869765,149.916866,NaN
min,16456.000000,37215.000000,18781.000000,1984.000000,169.000000,180.000000,533.000000,252.000000,NaN
25%,31676.250000,46632.750000,33202.750000,3348.500000,281.750000,425.000000,751.000000,336.750000,NaN
50%,50621.500000,55945.500000,81711.500000,4221.000000,383.500000,492.000000,998.000000,437.500000,NaN
75%,57072.750000,69049.750000,88433.750000,5484.500000,1118.750000,593.000000,1440.750000,584.250000,NaN
max,77954.000000,86222.000000,110267.000000,7889.000000,1783.000000,800.000000,1821.000000,732.000000,NaN

In [8]:
# Seleccinamos las filas que cumplen con dos condiciones: que el número de casos sea menor a 60000 y que el número de salidas sea mayor a 4500. Para esto, usamos el operador & para combinar las dos condiciones y creamos una nueva máscara de booleanos.
mask = (df.loc[:, 'Cases']< 60000) & (df.loc[:, 'Sorties']> 4500)
df[mask]

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1996,43553.0,55710,98423.0,5047,367.0,611.0,978.0,NaN,NaN
2003,31429.0,51389,33117.0,5192,263.0,409.0,672.0,496.0,NaN
2004,32418.0,59995,33460.0,5557,281.0,502.0,783.0,691.0,NaN
2005,29646.0,52741,30779.0,5635,324.0,521.0,845.0,603.0,NaN
2006,28151.0,45910,28583.0,5275,328.0,452.0,780.0,664.0,NaN
2007,26927.0,47517,26586.0,5200,300.0,492.0,792.0,732.0,NaN
2008,24213.0,44931,25475.0,4900,291.0,534.0,825.0,435.0,NaN
2009,23545.0,47497,24644.0,4882,261.0,555.0,816.0,578.0,NaN

### Creating new column

In [9]:
# Creamos una nueva columna en el DataFrame llamada "Saved per Sortie" que contiene el número de vidas salvadas por cada salida. Para esto, dividimos la columna "Lives Saved" entre la columna "Sorties" y asignamos el resultado a la nueva columna.
df.loc[:,'Saved per Sortie'] = df.loc[:,'Lives Saved'] / df.loc[:,'Sorties']